### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    id: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    summary: "Describes a Chaos event that gets generated when an unexpected event occurs\rin the Chaos engine.\rFor example, due to the cluster snapshot being inconsistent, while faulting\ra faultable entity, Chaos found that the entity was alreay faulted -- which\rwould be an unexpected event."
    fullName: azure-servicefabric.TestErrorChaosEvent
    source:
      id: azure-servicefabric.TestErrorChaosEvent
      path: lib\services\serviceFabric\lib\models\testErrorChaosEvent.js
      startLine: 25
      remote:
        branch: master
        path: lib\services\serviceFabric\lib\models\testErrorChaosEvent.js
        repo: 'https://github.com/Azure/azure-sdk-for-node.git'
    type: Class
    children:
      - 'azure-servicefabric.TestErrorChaosEvent.#ctor'
      - 'azure-servicefabric.TestErrorChaosEvent#mapper'
    langs:
      - js
  - id: 'azure-servicefabric.TestErrorChaosEvent.#ctor'
    uid: 'azure-servicefabric.TestErrorChaosEvent.#ctor'
    parent: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent()
    fullName: azure-servicefabric.TestErrorChaosEvent.TestErrorChaosEvent()
    summary: ''
    type: Constructor
    syntax:
      content: new TestErrorChaosEvent()
    langs:
      - js
  - uid: 'azure-servicefabric.TestErrorChaosEvent#mapper'
    id: 'azure-servicefabric.TestErrorChaosEvent#mapper'
    parent: azure-servicefabric.TestErrorChaosEvent
    name: mapper()
    summary: Defines the metadata of TestErrorChaosEvent
    fullName: azure-servicefabric.TestErrorChaosEvent.mapper()
    type: Function
    syntax:
      return:
        type:
          - object
        description: metadata of TestErrorChaosEvent
      content: function mapper()
    langs:
      - js
